
services:
  # db service
  postgres_local:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: portfolio_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # u≈ºywane tylko lokalnie

  # bcknd (flask) serwis  
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app # serwowanie aplikacji via Gunicorn
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:mypassword@postgres_local:5432/portfolio_db
      
      SECRET_KEY: '1234567890'
      JWT_SECRET_KEY: '1234567890'
      
      FLASK_APP: wsgi
    depends_on:
      - postgres_local

volumes:
  db_data: