
services:
  # db service
  postgres_local:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: portfolio_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # cache
  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  # bcknd (flask) serwis  
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app # serwowanie aplikacji via Gunicorn
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:mypassword@postgres_local:5432/portfolio_db
      REDIS_URL: redis://cache:6379/0 # address of redis inside container internal network
      SECRET_KEY: '1234567890'
      JWT_SECRET_KEY: '1234567890'
      FINNHUB_API_KEY: 'd3uj149r01qil4aqb7n0d3uj149r01qil4aqb7ng'
      FLASK_APP: wsgi
    depends_on:
      - postgres_local
      - cache

#  frontend:
#      # Lokalizacja, z której ma budować (katalog 'frontend')
#      build:
#        context: ./frontend 
#      # Mapowanie portu: 8080 na hoście Arch => 8080 w kontenerze (typowe dla Vue)
#      ports:
#        - "8080:8080"
#      # Mapowanie wolumenu, aby umożliwić Hot Reloading (zmiany kodu widoczne natychmiast)
#      volumes:
#        - ./frontend:/app
#      # Pamiętaj, aby serwis backendowy był dostępny dla frontendu
#     depends_on:
#        - web

volumes:
  db_data:
