
services:
  
  # db service
  postgres_local:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: portfolio_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  # cache
  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  # bcknd (flask) serwis  
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app # serwowanie aplikacji via Gunicorn
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:mypassword@postgres_local:5432/portfolio_db
      REDIS_URL: redis://cache:6379/0 # address of redis inside container internal network
      NOTIFICATION_BROKER_URL: ws://notification-broker:8001/flask-push
      SECRET_KEY: '1234567890'
      JWT_SECRET_KEY: '1234567890'
      FINNHUB_API_KEY: 'd3uj149r01qil4aqb7n0d3uj149r01qil4aqb7ng'
      FLASK_APP: wsgi
    depends_on:
      - postgres_local
      - cache

  # notifications broker
  notification-broker: 
    build:
      context: ./notification-broker
      dockerfile: Dockerfile
    ports:
      - "8001:8001" 
    environment:
      PYTHONUNBUFFERED: 1
    restart: always
  
  # price checker
  price-checker:
    build:
      context: ./price-checker
      dockerfile: Dockerfile
    environment:
      FINNHUB_API_KEY: 'd3uj149r01qil4aqb7n0d3uj149r01qil4aqb7ng' 
      DATABASE_URL: postgresql://postgres:mypassword@postgres_local:5432/portfolio_db
      NOTIFICATION_BROKER_URL: ws://notification-broker:8001/flask-push
    depends_on:
      - postgres_local
      - notification-broker
    restart: always

  # efficiency metrics (prometheus)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # interface port for Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro # configuration file
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - web

  # visualization (grafana)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # interface port for Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

#  frontend:
#      build:
#        context: ./frontend 
#      ports:
#        - "8080:8080"
#      volumes:
#        - ./frontend:/app
#      depends_on:
#        - web

volumes:
  db_data:
